name: Pages

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/pages.yml'
      - '**/*.swift'

jobs:
  deploy-docs:
  
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - run: bundle install --jobs=3 --retry=3 --deployment

    - name: Run jazzy
      run: |
        bundle exec jazzy \
          --module URLKit \
          --swift-build-tool spm \
          --author RIDI \
          --author_url https://www.ridicorp.com \
          --github_url https://github.com/ridi/URLKit.swift \
          --root-url https://ridi.github.io/URLKit.swift/URLKit \
          --output docs/URLKit

        bundle exec jazzy \
          --module RxURLKit \
          --swift-build-tool spm \
          --author RIDI \
          --author_url https://www.ridicorp.com \
          --github_url https://github.com/ridi/URLKit.swift \
          --root-url https://ridi.github.io/URLKit.swift/RxURLKit \
          --output docs/RxURLKit
        
        bundle exec jazzy \
          --module HTTPURLKit \
          --swift-build-tool spm \
          --author RIDI \
          --author_url https://www.ridicorp.com \
          --github_url https://github.com/ridi/URLKit.swift \
          --root-url https://ridi.github.io/URLKit.swift/HTTPURLKit \
          --output docs/HTTPURLKit

        bundle exec jazzy \
          --module RxHTTPURLKit \
          --swift-build-tool spm \
          --author RIDI \
          --author_url https://www.ridicorp.com \
          --github_url https://github.com/ridi/URLKit.swift \
          --root-url https://ridi.github.io/URLKit.swift/RxHTTPURLKit \
          --output docs/RxHTTPURLKit
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
